#!/usr/bin/env node

var Assert = require('assert')

var Fs = require('./')
var Path = require('path')

/*
//
// find all .js files with system `find` and `Fs.find`
//

var jscount = 0, total = 0;
Fs.find(process.env.HOME, {
  //follow: true,
  match_fn: function (path, stat, depth, cb) {
    //console.log(path)
    total++
    if (path.match(/\.js$/)) {
      jscount++
    }
    cb()
  }
}, function (err) {
  if (err) {
    console.log('ERR', err)
    process.exit(1)
  }
  console.log('find()', jscount, 'of', total)
  require('child_process').exec('find ' + process.env.HOME + ' | wc -l', function (err, findtotal) {
    findtotal = Number((findtotal || '0').trim())
    require('child_process').exec('find ' + process.env.HOME + ' -name \\*.js | wc -l', function (err, findjscount) {
      findjscount = Number((findjscount || '0').trim())
      console.log('find ~ -name \\*.js | wc -l', findjscount, 'of', findtotal)
      Assert.equal(jscount, findjscount)
      Assert.equal(total, findtotal)
    })
  })
})
*/

//
// mkdir_p ./HZ/foo./bar
//

Fs.mkdir_p('HZ/foo./bar', '0771', function (err) {
  if (err) {
    console.log('mkdir_p ERROR', err)
    process.exit(1)
  }
  Assert.ok(!err)
  Assert.ok(Path.existsSync('HZ'))
  Fs.rm_rf('HZ', function (err) {
    if (err) {
      console.log('rm_fr ERROR', err)
      process.exit(1)
    }
    Assert.ok(!err)
    Assert.ok(!Path.existsSync('HZ/foo./bar'))
    Assert.ok(!Path.existsSync('HZ/foo.'))
    Assert.ok(!Path.existsSync('HZ'))
  })
})
